// AUTO GENERATED FILE - DO NOT EDIT

const classNames = {
  'about': 'about',
  'about__hero': 'about__hero',
  'about__copy': 'about__copy',
  'about__eyebrow': 'about__eyebrow',
  'about__summary': 'about__summary',
  'about__actions': 'about__actions',
  'about__button': 'about__button',
  'about__button--primary': 'about__button--primary',
  'about__button--secondary': 'about__button--secondary',
  'about__grid': 'about__grid',
  'about__card': 'about__card',
  'app-shell': 'app-shell',
  'app-shell__header': 'app-shell__header',
  'app-shell__brand': 'app-shell__brand',
  'app-shell__logo': 'app-shell__logo',
  'app-shell__eyebrow': 'app-shell__eyebrow',
  'app-shell__title': 'app-shell__title',
  'app-shell__strapline': 'app-shell__strapline',
  'app-shell__session': 'app-shell__session',
  'app-shell__profile': 'app-shell__profile',
  'app-shell__profile-label': 'app-shell__profile-label',
  'app-shell__ghost-button': 'app-shell__ghost-button',
  'app-shell__nav': 'app-shell__nav',
  'app-shell__nav-link': 'app-shell__nav-link',
  'app-shell__nav-link--active': 'app-shell__nav-link--active',
  'app-shell__main': 'app-shell__main',
  'infolet': 'infolet',
  'infolet-icon-container': 'infolet-icon-container',
  'infolet-icon': 'infolet-icon',
  'infolet-content': 'infolet-content',
  'linklet': 'linklet',
  'linklet-icon-container': 'linklet-icon-container',
  'linklet-icon': 'linklet-icon',
  'linklet-content': 'linklet-content',
  'linklet-ref': 'linklet-ref',
  'linklet-ref-icon': 'linklet-ref-icon',
  'linklet-url': 'linklet-url',
  'linklet-hover': 'linklet-hover',
  'linklet-hover-icon': 'linklet-hover-icon',
  'linklet-hover-url': 'linklet-hover-url',
  'scrollpop': 'scrollpop',
  'hero': 'hero',
  'section': 'section',
  'section-content': 'section-content',
  'state-panel': 'state-panel',
  'state-panel__eyebrow': 'state-panel__eyebrow',
  'state-panel__action': 'state-panel__action',
  'state-panel--danger': 'state-panel--danger',
  'state-panel--warning': 'state-panel--warning',
  'textlet': 'textlet',
  'textlet-title': 'textlet-title',
  'textlet-icon': 'textlet-icon',
  'textlet-content': 'textlet-content',
  'trip-info': 'trip-info',
  'trip-info-icon': 'trip-info-icon',
  'clickable': 'clickable',
  'limit-width': 'limit-width',
  'node-bg': 'node-bg',
  'node-bg-node': 'node-bg-node',
  'heading-max': 'heading-max',
  'heading-large': 'heading-large',
  'heading-medium': 'heading-medium',
  'heading-small': 'heading-small',
  'line-break': 'line-break',
  'text': 'text',
  'view-stack': 'view-stack',
  'view-section__header': 'view-section__header',
  'view-section__eyebrow': 'view-section__eyebrow',
  'metric-grid': 'metric-grid',
  'feature-grid': 'feature-grid',
  'detail-grid': 'detail-grid',
  'metric-card': 'metric-card',
  'product-card': 'product-card',
  'order-card': 'order-card',
  'toolbar-card': 'toolbar-card',
  'view-form-panel': 'view-form-panel',
  'view-error-banner': 'view-error-banner',
  'view-success-banner': 'view-success-banner',
  'detail-card': 'detail-card',
  'cart-row': 'cart-row',
  'product-card__topline': 'product-card__topline',
  'order-card__topline': 'order-card__topline',
  'product-card__copy': 'product-card__copy',
  'product-card__tags': 'product-card__tags',
  'order-card__stats': 'order-card__stats',
  'cart-list': 'cart-list',
  'detail-list': 'detail-list',
  'product-card__subline': 'product-card__subline',
  'product-card__description': 'product-card__description',
  'order-card__note': 'order-card__note',
  'cart-row__copy': 'cart-row__copy',
  'product-card__pill': 'product-card__pill',
  'product-tag': 'product-tag',
  'order-card__status': 'order-card__status',
  'product-tag--warning': 'product-tag--warning',
  'product-card__actions': 'product-card__actions',
  'order-card__actions': 'order-card__actions',
  'view-form__actions': 'view-form__actions',
  'toolbar-card__search': 'toolbar-card__search',
  'toolbar-card__toggle': 'toolbar-card__toggle',
  'view-button': 'view-button',
  'view-button--primary': 'view-button--primary',
  'view-button--secondary': 'view-button--secondary',
  'view-button--ghost': 'view-button--ghost',
  'view-form': 'view-form',
  'view-form__grid': 'view-form__grid',
  'view-form__grid--triple': 'view-form__grid--triple',
  'detail-card--wide': 'detail-card--wide',
  'detail-card__eyebrow': 'detail-card__eyebrow',
  'cart-row__controls': 'cart-row__controls'
} as const;

export type ClassName = (keyof typeof classNames);
export type PossibleClassName = ClassName | false | null | undefined;

export function useClasses(...args: PossibleClassName[]): string {
  const validClass = (arg: PossibleClassName) => !!(arg && arg in classNames);
  const validClasses = args.filter(validClass) as ClassName[];
  return validClasses.map(arg => classNames[arg]).join(' ');
}

