// AUTO GENERATED FILE - DO NOT EDIT

const classNames = {
  'button': 'button',
  'cart-action': 'cart-action',
  'cart-action-full': 'cart-action-full',
  'cart-action-icon': 'cart-action-icon',
  'cart-action-secondary': 'cart-action-secondary',
  'cart-action-square': 'cart-action-square',
  'cart-actions': 'cart-actions',
  'category-list': 'category-list',
  'checkout-billing': 'checkout-billing',
  'checkout-details': 'checkout-details',
  'checkout-items': 'checkout-items',
  'checkout-summary': 'checkout-summary',
  'checkout-summary-details': 'checkout-summary-details',
  'checkout-summary-row': 'checkout-summary-row',
  'clickable': 'clickable',
  'dark': 'dark',
  'education-card': 'education-card',
  'education-card-content': 'education-card-content',
  'education-card-degree': 'education-card-degree',
  'education-card-grade': 'education-card-grade',
  'education-card-icon': 'education-card-icon',
  'education-card-icon-container': 'education-card-icon-container',
  'education-card-separator': 'education-card-separator',
  'education-card-title': 'education-card-title',
  'fly-pulse': 'fly-pulse',
  'footer': 'footer',
  'footer-content': 'footer-content',
  'heading-large': 'heading-large',
  'heading-max': 'heading-max',
  'heading-medium': 'heading-medium',
  'heading-small': 'heading-small',
  'hero': 'hero',
  'hero-background': 'hero-background',
  'hero-brand': 'hero-brand',
  'hero-content': 'hero-content',
  'hero-image': 'hero-image',
  'hero-subtitle': 'hero-subtitle',
  'infolet': 'infolet',
  'infolet-content': 'infolet-content',
  'infolet-icon': 'infolet-icon',
  'infolet-icon-container': 'infolet-icon-container',
  'input': 'input',
  'input-container': 'input-container',
  'jiggle': 'jiggle',
  'limit-width': 'limit-width',
  'line-break': 'line-break',
  'linklet': 'linklet',
  'linklet-content': 'linklet-content',
  'linklet-hover': 'linklet-hover',
  'linklet-hover-icon': 'linklet-hover-icon',
  'linklet-hover-url': 'linklet-hover-url',
  'linklet-icon': 'linklet-icon',
  'linklet-icon-container': 'linklet-icon-container',
  'linklet-ref': 'linklet-ref',
  'linklet-ref-icon': 'linklet-ref-icon',
  'linklet-url': 'linklet-url',
  'medicine-card': 'medicine-card',
  'medicine-card-content': 'medicine-card-content',
  'medicine-card-image': 'medicine-card-image',
  'medicine-card-image-placeholder': 'medicine-card-image-placeholder',
  'medicine-card-name': 'medicine-card-name',
  'medicine-card-price': 'medicine-card-price',
  'medicine-card-price-striked': 'medicine-card-price-striked',
  'medicine-card-price-text': 'medicine-card-price-text',
  'menu': 'menu',
  'menu-bottom-left': 'menu-bottom-left',
  'menu-bottom-right': 'menu-bottom-right',
  'menu-brand': 'menu-brand',
  'menu-brand-container': 'menu-brand-container',
  'menu-brand-image': 'menu-brand-image',
  'menu-button': 'menu-button',
  'menu-button-badge': 'menu-button-badge',
  'menu-container': 'menu-container',
  'menu-top-left': 'menu-top-left',
  'menu-top-right': 'menu-top-right',
  'navbar': 'navbar',
  'navbar-categories': 'navbar-categories',
  'navbar-container': 'navbar-container',
  'navbar-search': 'navbar-search',
  'navbar-search-container': 'navbar-search-container',
  'no-scrollpop': 'no-scrollpop',
  'node-bg': 'node-bg',
  'node-bg-node': 'node-bg-node',
  'open-source-card': 'open-source-card',
  'open-source-card-actions': 'open-source-card-actions',
  'open-source-card-content': 'open-source-card-content',
  'open-source-card-icon': 'open-source-card-icon',
  'open-source-card-info': 'open-source-card-info',
  'open-source-card-meta': 'open-source-card-meta',
  'open-source-card-mine': 'open-source-card-mine',
  'open-source-card-mine-container': 'open-source-card-mine-container',
  'open-source-card-repo': 'open-source-card-repo',
  'open-source-card-repo-text': 'open-source-card-repo-text',
  'open-source-card-title': 'open-source-card-title',
  'scrollpop': 'scrollpop',
  'section': 'section',
  'section-content': 'section-content',
  'social-link': 'social-link',
  'social-link-hover': 'social-link-hover',
  'social-link-hover-icon': 'social-link-hover-icon',
  'social-link-hover-url': 'social-link-hover-url',
  'social-link-icon': 'social-link-icon',
  'social-link-icon-container': 'social-link-icon-container',
  'socials-linklets': 'socials-linklets',
  'text': 'text',
  'textlet': 'textlet',
  'textlet-content': 'textlet-content',
  'textlet-icon': 'textlet-icon',
  'textlet-title': 'textlet-title',
  'theme-bubble': 'theme-bubble'
} as const;

export type ClassName = (keyof typeof classNames);
export type PossibleClassName = ClassName | false | null | undefined;

export function useClasses(...args: PossibleClassName[]): string {
  const validClass = (arg: PossibleClassName) => !!(arg && arg in classNames);
  const validClasses = args.filter(validClass) as ClassName[];
  return validClasses.map(arg => classNames[arg]).join(' ');
}

